# @package _global_

# order in which configs override each other (/* - denotes a relative search path)
defaults:
  - /base_gs
  - /dataset: openmvg
  - /initialization: point_cloud
  - /render: 3dgut
  - _self_

# overwrite of default parameters
val_frequency: 3000 # never validate
